filter {
  # IPv4 starts with a digit; IPv6 contains a colon (including ::1 loopback)
  if [server][address] =~ /^\d|:/ {
    if ![server][ip] {
      mutate {
        add_field => {
          "[server][ip]" => "%{[server][address]}"
        }
      }
    }
  } else if [server][address] =~ /^\D/ {
    if ![server][domain] {
      mutate {
        add_field => {
          "[server][domain]" => "%{[server][address]}"
        }
      }
    }
  }
}
